### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by neuromancer** [bradhannah/Ultima5Redux#1]
I think people will be more interested in testing this reimplementation and maybe collaborate with some code if you show its current state with some screenshots (even early ones!).

**Comment by bradhannah** [comment]
Sorry - just noticed this! I post updates on Twitter https://twitter.com/ThisSoftware and my dev blog here: https://u5redux.wordpress.com/

Honestly - play testing is super far away. At this point I don't think we could yet call it a game :)
