### ISSUE TITLE
SB: people hate you and avoid you, while guards want to arrest you after you murder someone in town!

### ISSUE THREAD

**Issue by bradhannah** [bradhannah/Ultima5Redux#114]

**Comment by bradhannah** [comment]
From @tanabi
If you kill someone in town, everyone will run away from you (except guards who will suddenly be magnetically attracted to you). Guards will arrest or fight. People, as I recall, won't talk to you -- I don't remember what they say exactly but they say just go away! or don't hurt me! or something like that.

**Comment by bradhannah** [comment]
People run away, guards chase you
If met by a guard you can go to jail or fight
If talking to an NPC they will be scared and not talk with you

**Comment by tanabi** [comment]
> People run away, guards chase you If met by a guard you can go to jail or fight If talking to an NPC they will be scared and not talk with you

This is almost a haiku :)

**Comment by bradhannah** [comment]
😂 I’m a poet and didn’t even know it!
