### ISSUE TITLE
Unable to start game

### ISSUE THREAD

**Issue by ShamblerDK** [bradhannah/Ultima5Redux#170]
I try to follow the installation procedure, but there's a part I don't understand:

You are able to put may Ultima 5 directories in these directory - you will be permitted to choose when launching the game For example my personal directory looks like
-> C:\games\Ultima_5\gold\*
-> C:\games\Ultima_5\britain\*
-> C:\games\Ultima_5\im_scared\*
I know this is kind of silly, but I just haven't gotten around to adding the option to choose your own base directory.

Is "may" supposed to be "many"?

And what exactly would final directory structure look like? Would it be "C:\Games\Ultima_5\SAVED.GAM"?

Whenever I start the demo, I can only choose a sub-directory from where I started the Unity client:
![image](https://user-images.githubusercontent.com/3033414/126497583-807ccd53-8a30-41bc-941d-8835f2a1de0d.png)

If I don't put the contents of the entire Ultima 5 base game directory into the "Saves"-folder, I get file not found errors in the log file.

When I put all the base game files into the "Saves"-folder, I get this:
![image](https://user-images.githubusercontent.com/3033414/126497892-41fecbe0-6719-4eaf-b5c0-4f5434185b81.png)

**Comment by bradhannah** [comment]
@ShamblerDK - I have completely redesigned the load/save/import functionality in the latest build. I hope to have new binaries up in the next few weeks for you to try. Takes all the guess work out of it going forward! I have added a new same game format which is a little more "magic", but still easily import legacy(original) save game files as a starting place.

**Comment by ShamblerDK** [comment]
> @ShamblerDK - I have completely redesigned the load/save/import functionality in the latest build. I hope to have new binaries up in the next few weeks for you to try. Takes all the guess work out of it going forward! I have added a new same game format which is a little more "magic", but still easily import legacy(original) save game files as a starting place.

That's great news! :D
