### ISSUE TITLE
Re-implement New-Order with new dialog foramt

### ISSUE THREAD

**Issue by bradhannah** [bradhannah/Ultima5Redux#218]

**Comment by bunnylin** [comment]
The current New Order system appears to soft-lock the game. The New Order highlight remains active after a successful or failed attempt, with no way to return to normal control. A re-implemented system will automatically take care of this bug.

**Comment by bradhannah** [comment]
Nice catch yeah, I didn't know it soft locked, but I am not surprised. That old system was one of the first things I implemented and a LOT has changed in terms of the architecture since.

**Comment by bradhannah** [comment]
Cleaned up and simplified. No more softlocks ;)
