### ISSUE TITLE
Some monsters can throw projectiles in overworld at Avatar (sea monsters)

### ISSUE THREAD

**Issue by bradhannah** [bradhannah/Ultima5Redux#227]

**Comment by tanabi** [comment]
Sea serpents, dragons, and pirate ships can all shoot at you on the overworld.

Also I'm not sure if you got this one, but don't forget bridge trolls :)

Thanks for making this -- even if I'm quietly watching, I'm cheering from the sidelines :)

**Comment by bradhannah** [comment]
Done, including dragons. Tracking bridge troll work witll be a separate ticket
