### ISSUE TITLE
SB: Lighthouse light beam should rotate!

### ISSUE THREAD

**Issue by bunnylin** [bradhannah/Ultima5Redux#250]
The lighthouses look cool! (The one in front of Minoc may be easiest to get to.) But the light effect at night should rotate around. Low priority, since it's mostly eye candy.

**Comment by bradhannah** [comment]
Agreed! I'm imagining a "spot" light which should emulate the lighthouse perfectly.

**Comment by bradhannah** [comment]
![Image](https://user-images.githubusercontent.com/47454550/202815974-ea5d5faa-57ca-4217-b492-37d0a7eb5c8b.png)

**Comment by bradhannah** [comment]
Now rotates around the lighthouse. I still want to do some visual tweaks - but it's going to mean splitting the lighthouse into two separate onbjects, so making a separate ticket for that.
