### ISSUE TITLE
SB: Bards Change into Music Mode

### ISSUE THREAD

**Issue by tanabi** [bradhannah/Ultima5Redux#252]
We mentioned this briefly and you went on to mention buccaneer's den.  I wanted to elaborate a bit on how the original game does it, because this actually shows up in a number of places (i.e. the west side kitchen in LB's castle is another place where a bard sits in a chair and sings).

I have observed that in the original game, if a bard somehow winds up in ANY chair that faces south that DOESN'T have a plate of food on it (i.e. if the bard walks through a chair during his daily schedule, even in passing) he'll go into "singing mode" as soon as he hits the chair.  I think the logic in the game is basically:

```
if in south facing chair:
    if table with food is south of here:
         eat animation
    else if bard:
          play lute
    else
           sit
```

I think a slight improvement to this logic would be to say "else if bard and no table to the south" which would stop most cases of accidental spontaneous barding during the course of day to day travel.  However, it's clear that the original game doesn't use "magic bard spots" or anything, it's simply a combination of bard + south facing chair - food :)

**Comment by bradhannah** [comment]
Awesome breakdown and thanks for the pseudo code too!

**Comment by bradhannah** [comment]
I have made the improvements in your code. I just have to add special handling for the actual music bits now. I am thinking something solemn, instead of whatever the hell it is that he plays now!
