### ISSUE TITLE
U5 Quirks

### ISSUE THREAD

**Issue by tanabi** [bradhannah/Ultima5Redux#253]
The purpose of this ticket is to record some U5 quirks that I remember.  I will build this ticket so that it can be split into smaller tickets if it makes sense.  There's probably overlap with things you already have done.  I'm not going to mention things that are core gameplay (i.e. the grapple for instance, playing the harpsicord, magic skull keys in Minoc, shrine of spirituality in moongates, etc.)

Waterfall Falling
If you are in a skiff or magic capret and you enter the square above a waterfall, it "sucks you down" and damages everyone in the party the same way as if they got hit by a cannon, stepped on lava, etc.

One waterfall sucks you into the underworld, I don't remember off-hand which one (I think it's west of the castle).

Magic Axe in Jhelom
There's a stump outside east wall that if you search it, you can get magic axes.  I think you can only get one?  They don't regenerate.

Gems in Paws
There's a stump in Paws that has gems in it.  I think it's somewhere near the Guild store, like outside the door.  Maybe there's some way to derive which tiles have something to search for in the data files but I'm not sure.  These don't regenerate either as I recall.  I think there's also a ring in the same stump as I think about it more?

Wishing for Horses
All wells prompt you to make a wish, however I think only the well in Empath Abbey will grant wishes (not 100% sure on that, it might be all wells, but I know for sure Empath Abbey it works...Paws as well I think, but not Iolo's hut?) will grant them.

You can get a horse if you wish for a horse, or a list of other words ("Ferrari", "Lamborghini", and others -- they are in DATA.OVL).  I can figure out this list if needed.

Smith the Horse
Smith the Horse shows up in Iolo's hut, but isn't there when you first load the game.  I'm not sure what triggers him -- is it when you leave Iolo's hut and come back?  Does he show up after x number of days?  I never put the time into figuring out the behavior, but if you'd like me to figure it out I'd be happy to.

Climbing Fences
You can K-climb fences!  Like the fences used in farms and whatnot.

Food in Empath Abbey
The cook in Empath Abbey will give you a "taste" of the soup he's making (I think it's shark fin soup, but that might be someplace else).  Most of the cooks that give you a taste of their soup, it doesn't impact your food count -- however, for whatever reason, this one cook DOES impact your food count.  You can keep asking him for a taste and keep getting 1 more food with no karma loss.

PIcking Up Moongate Stones
You can search the ground where a moongate is to pick up its stone, so the moongates are mobile and can be placed in both the overworld and underworld (But only on grass)

Skiffs come out of Frigates
If a Frigate isn't next to land and you x-exit it, you get a skiff.  The game manual claims there's only one skiff per frigate, but I've actually never tried to spawn more skiffs out of a frigate so maybe the manual lies.  It's worth trying (I can try it if you want).  You can also put the skiff back into the frigate.

People Hate You when the Shadowlord is in Town
If the shadowlord is in town, a number of things happen.  You get the eerie music when you enter, and the towns people won't talk to you.  They all say "Begone, wretch!" and, as a kid, I always figured they gave you a titty-twister because as I recall they injure your party as well.  There's probably other effects that I am forgetting.

Guards Harass you for Blackthorne
The guards will demand taxes.  If you can't pay, you go to jail.  The logic here is fairly complex -- for instance, in Minoc, they take half your money, whereas I think most places it is a fixed rate.

Spyglass (and mounted telescopes in towns)
The spyglass will show you where shadowlords are, but only at night -- during the day it injures the person looking through it.  Thou doth seeth the sun!

People run away from you when you murder someone
If you kill someone in town, everyone will run away from you (except guards who will suddenly be magnetically attracted to you).  Guards will arrest or fight.  People, as I recall, won't talk to you -- I don't remember what they say exactly but they say just go away! or don't hurt me! or something like that.

Levels of Guard Attraction
Guards seem to have 3 modes that I can tell.  Regular scheduled activities where they stand still or roam and ignore the player, "magnetically attracted" which is after the player commits a crime (more on that), or partially attracted which is how blackthorne tax guards are.

When I say "partially attracted" I mean, the guard seems to have logic where it wants to come intercept you but it doesn't go SUPER out of its way to do so ... i.e. it follows its patrol, but unless you're within X squares of it, it won't start hunting you. Also I think only one guard per town is the "tax guard" -- there will be guards standing at the gate, for instance, that ignore you.  Not all towns have a tax guard -- Britain for instance doesn't, nor do the small towns, or LB's castle.

I could be forgetting this behavior somewhat, if it's something you haven't already explored I can codify it better.

What are crimes?  There's quite a few.  Note that not all crimes decrease karma.

Murder - that's a big one.  Remember you can insta-kill people who are in bed!  Does decrease karma

Firing a cannon -- if you fire a cannon the guards will hate you (however I think the people still interact with you normally, need to double check).  Pretty sure this doesn't lose karma.  By the way, you can fire cannons, push the cannons (including turning them around if you push them against a wall), and cannons blow up doors :)  And it insta-kills NPCs.

Freeing prisoners -- you can free prisoners in the stocks and I think that pisses the guards off (don't remember though, easy to test in Yew).  The prisoners will say something like "I thank thee" and start bumbling around kind of dumbly, you can't talk to them after they are free.  I don't recall if this impacts karma one way or another.  You can also free people who are shackled to the wall.

Certain conversational interactions - this happens most notably in Blackthorne's castle.  If you have the badge on, you can talk to certain people, and if you're not sufficiently cruel or they otherwise suspect you they yell GUARDS and the guards get pissed off.  However I think there's a few other places.

Fountains
You can drink from fountains.  On the surface this doesn't do anything, in dungeons it can have effects.

.... and that's a start.  I've gotta go do some day job work now, but there's even MORE crap I remember.  If this is too much / not helpful then please let me know.  Also if you need me to hunt anything down better, I'd be happy to.

**Comment by tanabi** [comment]
More stuff I remember:

Bridge Trolls

```
Thou doth spyeth trolls under the bridge!
Iolo sneaks across...
```

This little sequence is so cool.  It's so tense watching those dots slowly come out, especially when you're a new characters and trolls are still scary.  I'm not sure if the character dexterity or anything has anything to do with bridge-sneaking or if it is purely random.

Pushing Stuff
You can push chairs, barrels, foot lockers, and cannons.  I think pushing things in dungeons can also have effect, but I don't remember.  If an object hits the wall, it reverses direction and swaps spots with the player and I think it says "Swapped places!" or something like that.  Chairs rotate to point in the direction they are pushed.    There might be other objects you can push ... maybe people too? -- I don't remember entirely.

Walking Through Fireplaces
You can walk through fireplaces, and they hurt the whole party.

Glass Swords
There's glass swords in the serpent's spine mountains -- the grass spot in the mountains northwest of LB's castle.  You can search and pick one up as long as you don't already have one in inventory.  Notoriously, you can search, get a sword, equip it, search again, get another, equip it, etc. until everyone has a glass sword + you have one spare in inventory.

Mirrors have reflections
You've probably already noticed this one, but if you stand in front of a mirror you see a reflection.  Of course LB is trapped in a mirror at the end so this might count as core gameplay and violate my rule of only mentioning things that are oddities.

More Searchable Spots
Many book-cases have things you can search for.  I.e. the book cases in the shipyard in (East?) Brittany, many book cases in Moonglow, etc.  If an exhaustive list of places you can search is necessary I can probably come up with it fairly quickly, I think I have most of them memorized as young-me basically searched every single tile in the whole game ;)  However hopefully we can derive this from the OVL files.

Beds also sometimes have things in them -- barrels, foot lockers, book cases, beds -- I think realistically anything can be searched in U5 and potentially have something so its not so much of a "searchable object" flag as it is a "something is at x,y location" flag.  More than one thing can be found if you keep searching in some cases.

Shadowlord Combat
Shadowlords have their own "combat map" that has barriers in it.  The barriers can be dispelled by the scepter as I recall, and a shadowlord can be "killed" with a glass sword (which removes him from the town but of course he can come back).  I am fairly sure killing the shadowlord counts like killing a person and the guards/town still hates you (though I'd need to double check that).

Ruined Shrines
If you go to blackthorne's castle and you give him the mantras he is looking for, he will destroy the shrine (As well as cut your companion in half for a rare perma-death).  Shrines are restored by Y-elling the word of power when standing next to them.  I'm not sure if the shrine of spirituality can be destroyed -- I've never burned through all the shrines at Blackthorne's to find out but that would be an interesting experiment.

H.M.S Cape Plans
Mentioned above is searching the shipyards.  You can get plans to make your ship go faster when the sails are out.  I don't know if it persists per boat or if you have to re-run the scroll each time you board any ship, I don't remember that part.  In U4 you had to re-mount the wheel each time you boarded ship which was the U4 equivalent, but U5 may be different.

.... I think that's all.  Unless I randomly come up with more.

**Comment by bradhannah** [comment]
Amazing list! By all means keep them coming if you think of anymore! Will definitely want to get them each in individual tickets, but this is a great place to gather them!

Also, the following "should" be working presently. If any of them are not, then it's a bug.
-=-=-=-
Pushing Stuff
Mirrors have reflections
Skiffs come out of Frigates
PIcking Up Moongate Stones
Climbing Fences

**Comment by tanabi** [comment]
Here's another weird one I was thinking about this morning.

Okay, so as a kid I used to "roleplay" in this game and one thing I did was I basically took over my own town.  One of the Britany's (I think east Britany .. its the one that doesn't have an inn and doesn't have the shipyard) only has one guard in the town.  So what I would do is I would kill the guard in his sleep, and now it's my town!  Yarr!

Anyway, for whatever reason after that I would loiter in this town for in-game days.  I'd wander around town, simulating my own 'routine' like I was an NPC.  Except of course all the other NPCs are terrified of me.  Why I did this?  I have no bloody clue now, clearly I had too much time as a kid.

Something really weird happens if you do this, though.  Eventually, the NPCs forget your crime partially.  As I recall (and I'd need to experiment to check the behavior) they eventually stop trying to run away from you but they still won't talk to you.  And weirder still, if you wait long enough, the *guard* will come back and arrest your butt :)  I remember when that happened I totally freaked out, I was not expecting that one!

I'm not sure it is a behavior we want to bother emulating, and I'm also not sure if it's a behavior only in one port (I'm pretty sure I did this on the C64 but not 100% sure), but it's a very curious one and honestly one that both fascinated me and probably isn't something a lot of people saw.  It could even be a couple of bugs and not exactly intentional behavior for all I know.

**Comment by tanabi** [comment]
Guard hates you on top of LB's castle
The guard on LB's castle roof will chase you around and force a conversation.  There's a few characters in the game that can force a conversation (like I think there's someone who collects donations in Minoc that can) but this guard is unique in that, after forcing the conversation, you have X number of turns to get away from him before he goes into arrest mode.

Once he's in arrest mode, I'm not sure if that counts as a "crime" (i.e. all the guards are pissed off) or only he's pissed off.  But it's a weird behavior that I think only happens with this one guard in this one place.

**Comment by tanabi** [comment]
Killing Rats Isn't a Crime
To make things a little more complex, there are a (very few) cases where townspeople and monsters reside on the same map.  If you use the blanket logic of "killing in a town is murder" then that won't be completley correct.  In Yew, there's rats in the basement you can kill to no ill effect on karma/townsfolk.  I think also if you kill the gargoyles in BT's castle (or more likely put on invis. rings and make them flee cause those are probably the hardest enemies in the game) nobody gets mad at you as I recall.

I think there's also a few of the small village maps that have rats or other monsters; none of these count as murder.

There's one map where there is a talking rat, and one map where there is a talking demon (actually there's at least a couple maps with talking demons).  I'm not sure if killing these things count as murder.  One of these demons (the one in the keep where you get the well) attacks you no matter what happens, so that one might just be a regular monster with a 'starts a conversation' trigger on it, as opposed to the demon who lives in a hut in the desert who is 100% friendly.

Notoriously there's some kids in a dungeon that you can kill.  Dungeon murders never impact karma as I recall.

You could probably use the blanket logic of 'if something attacks YOU, it isn't murder' since I think that may be closer to the truth?  For example, in LB's castle there are prisoners in the basement that, if freed, will attack you and they don't impact karma.  I think there's also a fighter somewhere that, if you talk to him, he's like "leave me alone" and if you keep talking to him he'll eventually fight you -- I don't know if that counts as murder or not (... my recollection is that it DID count as murder in that case).

Ack this is rambling and I'm feeling like its not very helpful because I'm using "somewhere" and "as I recall" a little too often :)  But there's a lot of facets to what is actually 'murder' in this game, just like in RL. :D

**Comment by bradhannah** [comment]
Thank you so much for the huge list @tanabi !!!
I wanted you to know I have slapped each of the ones I haven't completed in individual issues. I have added a new label called "Specific Behaviour" to describe a behaviour that is... uhhhh.. specific ;)
https://github.com/users/bradhannah/projects/6/views/17

If anymore come to mind, feel free to submit tickets with the "Specific Behaviour" tag 

Thanks again!
