### ISSUE TITLE
Friendlier UNIX instructions (for MacOS and Linux)

### ISSUE THREAD

**Issue by hackerb9** [bradhannah/Ultima5Redux#297]
The README says to use `chmod` to mark the downloaded file as executable. This should not be necessary. I suspect the cause of the problem is that the ZIP format cannot handle UNIX permissions and removes the execute bit. A solution would be to distribute U5R as a `.tgz` file (gzip compressed archive) instead. 

It would also be nice if the build system would make a symbolic link ("alias") to the executable with a shorter name. For example,

    ln  -s  UltimaVRedux-Linux-URP-Feb-10-2022.x86_64  u5r

That way UNIX folk who use the command line could simply run `./u5r` instead of ./UltimaVRedux-Linux-URP-Feb-10-2022.x86_64.

**Comment by bradhannah** [comment]
Thanks for the advice @hackerb9!

I still have a yucky binary name, but the tar.gz fixed the execute flags in Mac and Linux installs which was the biggest hurdle by far. I updated the install and run instructions in the Readme (https://github.com/bradhannah/Ultima5Redux/blob/master/README.md)

**Comment by hackerb9** [comment]
Hurray! 

Thanks for updating the instructions in the Readme. There is a typo that you might want to fix in step 3 which attempts to cd (change directory) to the .tar.gz file.  I'd also suggest putting the recommended download (Vulkan) first, adding links for the latest release, dropping the reference to GNOME and XFCE, and mentioning how to begin a new game. Here's some markdown you can cut and paste into the README. (Note that the links I created for the latest .tar.gz files will work once there is an official release). 

----
# Linux

1. [Download](https://github.com/bradhannah/Ultima5Redux/releases) Linux version:
    [u5test-linux.tar.gz](https://github.com/bradhannah/Ultima5Redux/releases/latest/download/u5test-linux.tar.gz) (Vulkan, recommended), or
    [u5test-ogl-linux.tar.gz](https://github.com/bradhannah/Ultima5Redux/releases/latest/download/u5test-ogl-linux.tar.gz) (OpenGL) 
3. Untar the game
    `tar xzvf u5*.tar.gz`
5. Change to the game directory:
    `cd u5*/`
7.  Execute game 
    `./u5test-linux.x86_64`

_Note:_ To begin a new game, choose **Import From Legacy Save** and select the `INIT.GAM` file that came with your [Ultima 5 disks](https://www.gog.com/en/game/ultima_456).
