### ISSUE TITLE
OpenGL support on Linux

### ISSUE THREAD

**Issue by roostercactus** [bradhannah/Ultima5Redux#327]
Hi, just curious...is OpenGL supported?  Or just Vulkan?  I have an old laptop with a GPU (Quadro 2000M) that doesn't support Vulkan.  So running the latest Linux builds fail with a Vulkan error.  I tried to pass '-force-opengl' on the command line but that segfaults.  

Here's the log when I force opengl:

Mono path[0] = '/appl/temp/software/u5r/UltimaVRedux-Linux-Jan11-2022/UltimaVRedux-Linux-URP-Jan-11-2022_Data/Managed'
Mono config path = '/appl/temp/software/u5r/UltimaVRedux-Linux-Jan11-2022/UltimaVRedux-Linux-URP-Jan-11-2022_Data/MonoBleedingEdge/etc'
Found 2 interfaces on host : 0) x.x.x.x 1) x.x.x.x
Multi-casting "[IP] x.x.x.x [Port] 55470 [Flags] 2 [Guid]  [EditorId]  [Version] 1048832 [Id] LinuxPlayer(13,x.x.x.x) [Debug] 0 [PackageName] LinuxPlayer [ProjectName] Ultima5Redux3D" to [225.0.0.222:54997]...
Preloaded 'lib_burst_generated.so'
Display 0 '0': 1920x1080 (primary device).
Unable to load player prefs
Desktop is 1920 x 1080 @ 60 Hz
Initialize engine version: 2021.2.7f1 (6bd9e232123f)
[Subsystems] Discovering subsystems at path /appl/temp/software/u5r/UltimaVRedux-Linux-Jan11-2022/UltimaVRedux-Linux-URP-Jan-11-2022_Data/UnitySubsystems
Forcing GfxDevice: OpenGL Core
Forced GfxDevice 'OpenGL Core' was not built from editor, shaders will not be available
PlayerInitEngineGraphics: InitializeEngineGraphics failed
Failed to initialize player
Caught fatal signal - signo:11 code:1 errno:0 addr:(nil)
Obtained 10 stack frames.
#0  0x007f8fbe194730 in funlockfile
#1  0x007f8fbfbadf76 in void std::vector<unsigned int, std::allocator<unsigned int> >::_M_assign_aux<__gnu_cxx::__normal_iterator<unsigned int*, std::vector<unsigned int, std::allocator<unsigned int> > > >(__gnu_cxx::__normal_iterator<unsigned int*, std::vector<unsigned int, std::allocator<unsigned int> > >, __gnu_cxx::__normal_iterator<unsigned int*, std::vector<unsigned int, std::allocator<unsigned int> > >, std::forward_iterator_tag)
#2  0x007f8fbf88086b in std::_Rb_tree<int, int, std::_Identity<int>, std::less<int>, std::allocator<int> >::_M_erase(std::_Rb_tree_node<int>*)
#3  0x007f8fbf87d129 in std::_Rb_tree<int, int, std::_Identity<int>, std::less<int>, std::allocator<int> >::_M_erase(std::_Rb_tree_node<int>*)
#4  0x007f8fbf87cb05 in std::_Rb_tree<int, int, std::_Identity<int>, std::less<int>, std::allocator<int> >::_M_erase(std::_Rb_tree_node<int>*)
#5  0x007f8fbfa9e0af in void std::vector<std::pair<int, bool>, std::allocator<std::pair<int, bool> > >::_M_realloc_insert<std::pair<int, bool> >(__gnu_cxx::__normal_iterator<std::pair<int, bool>*, std::vector<std::pair<int, bool>, std::allocator<std::pair<int, bool> > > >, std::pair<int, bool>&&)
#6  0x007f8fbf818895 in std::vector<int, std::allocator<int> >::_M_default_append(unsigned long)
#7  0x007f8fbfd110b5 in PlayerMain(int, char**)
#8  0x007f8fbdfe609b in __libc_start_main
#9  0x00000000201029 in _start

Here's some info on my opengl installation if it matters:  

glxinfo | grep -i version
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
OpenGL core profile version string: 4.6.0 NVIDIA 390.144
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL version string: 4.6.0 NVIDIA 390.144
OpenGL shading language version string: 4.60 NVIDIA
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 390.144
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

It's no big deal if it only works with Vulkan, just wanted to check.  Thanks!

**Comment by bradhannah** [comment]
Sorry! Not sure how I missed this. I don't have a great answer yet - but in a few weeks I will have a stable'ish build and test drive with the Linux folks again! I'll let you know when the binary drop.s

**Comment by bradhannah** [comment]
Definitely no promises it will work first time - I don't have a Linux system to test on. But here is an OpenGL build for Linux to test out. No hurry :)

https://github.com/bradhannah/Ultima5Redux/releases/download/Aug-13-2022-PreAlpha/u5test-ogl-linux.tar.gz

**Comment by tanabi** [comment]
This worked, though was actually slower for me than the normal build.  However, I don't have any special video hardware on my linux machine so that may be because my video system isn't up for it.  It's still playable though.

**Comment by bradhannah** [comment]
I wonder if I made a release build if it may speed it up. I kinda thought I
found the sweet spot for great performance.

Either way, thank you for testing it out!

**Comment by bradhannah** [comment]
Now that I have a recipe I will close this up and make sure I generally include an OpenGL release when I send out releases! Thanks again for testing @tanabi !

**Comment by roostercactus** [comment]
Hi, thanks for the Linux opengl version.  It works for me as well.  It's a little slow...but my laptop is ten years old.  I know this issue is closed but wanted to say thanks and this software is great.
