### ISSUE TITLE
Support or include support for 'Modding' the game.

### ISSUE THREAD

**Issue by cambragol** [bradhannah/Ultima5Redux#35]
If the game is essentially being rewritten, it would be nice to make the addition of additional content, "modding", easier, should someone feel inclined to add additional content.

The original is not very "mod" friendly, as many important bits are hard coded.

If Redux could put data for location, items, schedules etc. into external files, adding new towns, quests or content would become feasible.

**Comment by cambragol** [comment]
I tried to add this enhancement suggestion before accepting the invite to contribute, to see if it would work, however it did not. So labels can only be added by members of the repository. Hm.

In any case, the suggestions stands! I know some folk who'd love to build upon Ultima V in some way.

**Comment by bradhannah** [comment]
We will need to break it down further to be a more manageable notion. 

For example I have many JSON formatted data files that are currently embedded into the build as opposed to being stored and read directly from disk during launch. I "delta" JSON could be applied for further changes. These data files currently include:

InventoryDetails - item descriptions and sprite references
TileData - describes the tiles and already supports new tiles (see #512 in the tile list) - although separate sprites and configs would be extra work
TileOverrides - used when my "guessing" algorithm doesn't work properly and we need to force a floor tile to a different tile type

These are the ones so far - although I suspect you also mean NPC conversations and maybe even new NPCs.  

I will say no to this exact issue, and instead I think we could describe each module capability separately to make it easier to digest?
