### ISSUE TITLE
Fix doors in classic mode

### ISSUE THREAD

**Issue by bradhannah** [bradhannah/Ultima5Redux#407]

**Comment by bradhannah** [comment]
I just need to pick a model and stick to it. Probably like the old school doors.

**Comment by bradhannah** [comment]
![image](https://user-images.githubusercontent.com/47454550/200201758-be769a2f-e49b-4a55-ad4a-8d016deb20c3.png)
![image](https://user-images.githubusercontent.com/47454550/200201768-9b1cf544-3f81-4526-9355-46dd9ef37978.png)

**Comment by bradhannah** [comment]
Here you go @cambragol! The neat thing about it is they are actually still voxels, so they maintain some bits of their 3d properties including some shadows (when I want them) and y value for layering affects.

**Comment by bradhannah** [comment]
![image](https://user-images.githubusercontent.com/47454550/200201834-72ecab09-1137-403d-bb2f-da69a1bed322.png)

**Comment by tanabi** [comment]
This is really amazing, good job <3
