### ISSUE TITLE
Get food from a table

### ISSUE THREAD

**Issue by bradhannah** [bradhannah/Ultima5Redux#93]

**Comment by bunnylin** [comment]
Also get food from fields! But for some reason it may cost karma.

**Comment by tanabi** [comment]
> Also get food from fields! But for some reason it may cost karma.

Do you want some jerk stealing your fields? :)

Also when you're sitting at a table with food, the original game has an eating animation.  (and when bards sit on a chair that's facing south they start playing lute).

And randomly, the cook at Empath Abbey will give you shark fin soup.  And each time you do, you get a unit of food.  It's the (only?) way to get free food without it costing karma.

**Comment by bradhannah** [comment]
I actually did implement the eating animation ;) aware of that dang bard in Buc Den that play's lute. These are the finer details I am really appreciate you pulling out because they are so easy to miss!

Not familiar with the shark fin soup, I will do some tests. But I may need to change it to something less cruel!

**Comment by bradhannah** [comment]
Eating from tables implemented.

Looking at wheat in the field presently.

**Comment by bradhannah** [comment]
Can now pick crops. 

The bard will be taken care of in another ticket.

Fun fact though - there is actually a MINSTREL NPC type separate from a Bard. It just happens that the game draws it as a Bard until it sits in that down facing chair. In my version presently he walks around playing music everywhere he goes lol

**Comment by tanabi** [comment]
> Fun fact though - there is actually a MINSTREL NPC type separate from a Bard. It just happens that the game draws it as a Bard until it sits in that down facing chair. In my version presently he walks around playing music everywhere he goes lol

That IS a fun fact.  As a kid, I used to be really fascinated by those guys, since they made the game feel so 'alive' and I was playing it on a C64 so that was the only music you got.  I'd sit in the bar humming along.  Jeez that's what being a nerd-kid with no friends was back in the 80's.  And it was a decent little tune.

On PC, they just sounded like they were doing Morse Code as fast as possible :D
